version: "2"
linters:
  default: all
  disable:
    # Re-enable and address one at a time.
    - cyclop            # cyclomatic complexity
    - dupl              # duplicate code fragments
    - forbidigo         # forbidden identifiers
    - funlen            # long functions
    - gochecknoglobals  # global variables
    - gocognit          # cognitive complexity
    - gocritic          # bugs, performance, and style issues
    - gocyclo           # cyclomatic complexity
    - gosec             # security problems
    - lll               # long lines
    - maintidx          # maintainability index
    - mnd               # magic numbers
    - nestif            # deeply nested if statements
    - revive            # drop-in replacement for golint
    - varnamelen        # variable name length for its scope
